Render point cloud from color and depth images
ReOT20/SLAM_MMSS22 pull request #1
Opened 2022-07-08 17:48 UTC by ReOT20

2022-07-11 07:58 UTC, achains requested changes
В целом всё неплохо, молодец. Есть небольшие замечания, которые легко исправить.

И ещё одно: Почему у вас две основные ветки (master и main), давайте в будущем ветки, в которых мы выполняем какое-то задание называть так, чтобы можно было понять что собственно мы там делаем.

2022-07-11 07:58 UTC, achains commented on rgbdtopcd/pointcloud.py
> +from cv2 import IMREAD_ANYDEPTH
Принято сначала писать все `from import`, а затем уже `import` (или наоборот, но не перемешивать их)

2022-07-11 07:58 UTC, achains commented on rgbdtopcd/pointcloud.py
> +K = np.array([[481.20, 0., 319.50, 0.],
Что такое K? Давайте дадим переменной более говорящее название

2022-07-11 07:58 UTC, achains commented on rgbdtopcd/pointcloud.py
> +    z = d/5000
5000 это [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)). Для подобных констант лучше заводить свои переменные с говорящим названием

2022-07-11 07:58 UTC, achains commented on rgbdtopcd/pointcloud.py
> +colors = np.array([[0.]*3]*height*width)
Для создания нулевой матрицы в numpy есть своя функция, давайте применим здесь её

2022-07-11 07:58 UTC, achains commented on rgbdtopcd/pointcloud.py
> +for i in range(height):
А давайте попробуем переписать без циклов. Numpy умеет в быстрые арифметические операции над матрицами. (Поэлементное сложение/умножение и тд)

2022-07-11 21:16 UTC, ReOT20 commented
Про название ветки увидел, согласен, сделано неправильно, но сейчас  уже ничего с ним не  делал, так как при измменении имени реквест закроется

2022-07-12 03:40 UTC, DmiitriyJarosh requested changes

2022-07-12 03:40 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +CalibrationMatrix = np.array([[481.20, 0., 319.50, 0.],
давайте придерживаться кодстайла, где мы либо не переносим, либо переносим каждый уровень вложенности

2022-07-12 03:40 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +o3d.visualization.draw_geometries([pcd])
в конце питон файла должна быть пустая стркоа, установите себе pep и прогоняйте файл перед коммитом на соответсвие стандарту pep 8

2022-07-12 03:40 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +o3d.visualization.draw_geometries([pcd])
pycharm такое делает из коробки

2022-07-12 03:40 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +color_raw = np.asarray(cv2.imread('annot.png'))
почитайте про` if __name__ == "__main__":`

2022-07-12 03:40 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +color_raw = np.asarray(cv2.imread('annot.png'))
cv2 imread какой формат возвращает? правда что нужно еще кастить к np.array?

2022-07-12 03:40 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +height = color_raw.shape[0]
давайте пользоваться присваиванием покомпонентно - `heightб width = color_raw.shape[:2]`

2022-07-12 03:40 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +colors = color_raw.reshape(height*width, 3)[:, ::-1]/256
вокруг операторов ставим пробелы

2022-07-12 03:40 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +colors = color_raw.reshape(height*width, 3)[:, ::-1]/256
а для чего  ::-1?

2022-07-12 03:40 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +colors = color_raw.reshape(height*width, 3)[:, ::-1]/256
если это перегонка в другой формат цвета, то лучше это делать встроенной функцией opencv - она читабельнее

2022-07-12 03:40 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +InvCalibrationMatrix = np.linalg.inv(CalibrationMatrix)
зачем это в глобальных переменных? один раз используем ведь даже

2022-07-12 03:40 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +    return data[:, :3]
код функции очень сложный и непонятный, либо переписываем проще, либо коммент к каждой строке - что там делается + doc string в начале функции - с описанием краткой схемы работы

2022-07-12 22:33 UTC, achains requested changes
Молодец, код становится всё приятней читать! 

Два общих замечания:
1) Названия коммитов должны быть осмысленными. Не "_rgbd to pcd review 2 fixes_", а что-то в духе "_main function, comments_". В общем, по истории коммитов должно быть примерно понятно что именно менялось в коде.

2) Кажется, что форматтер так и не был запущен. Точно не хватает пробелов в местах арифметических операций. Можете почитать про [Black](https://github.com/psf/black)

2022-07-12 22:33 UTC, achains commented on rgbdtopcd/pointcloud.py
> +    # cоздаём двумерный индексный массив
Комментарии в сложных функциях это прекрасно, но они должны прояснять какие-то неочевидные моменты. Золотая середина придет с опытом, но старайтесь делать комментарии более осмысленными :)

Конкретно в этом случае у Вас есть переменная с говорящим названием IndicesArray (в названии которой у Вас опечатка), и далее Вы её как-то инициализируете. Возможно стоит пояснить как именно, а не просто расписывать и так очевидный момент

2022-07-12 22:33 UTC, achains commented on rgbdtopcd/pointcloud.py
> +    # объеденяем данные глубины с координатами
объед**И**няем

Вообще я буду настаивать на комментариях на английском языке, всё же так свои мысли Вы сможете донести до гораздо большего числа людей :)

2022-07-13 18:01 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +    # объеденяем данные глубины с координатами
согласен, все комменты на русском не засчитываются

2022-07-13 18:08 UTC, DmiitriyJarosh requested changes

2022-07-13 18:08 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +    CoordsArray = np.append(
переменные с маленькой буквы

2022-07-13 18:08 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +    # normalizing depth by image scale factor
почему нельзя сначала было нормализовать? так вы услождняете код какой то матричной операцией, а так просто поделили бы массивчик

2022-07-13 18:08 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +    CoordsArray = np.append(
можем от np.append уйти?

2022-07-13 18:08 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +    raw = np.array([data[:, 3]]).T
этот кусок выглядит непонятно, для чего мы это делаем?

2022-07-13 18:08 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +        [
матрицу в константу

2022-07-13 18:08 UTC, DmiitriyJarosh commented on rgbdtopcd/pointcloud.py
> +        [
или в аргумент

2022-07-22 16:39 UTC, achains approved these changes

2022-07-23 10:29 UTC, merged